[workspace]
members = [
    "crates/ragu",
    "crates/ragu_arithmetic",
    "crates/ragu_circuits",
    "crates/ragu_core",
    "crates/ragu_gadgets",
    "crates/ragu_macros",
    "crates/ragu_pasta",
    "crates/ragu_primitives",
]

resolver = "2"

[workspace.dependencies]
