[book]
authors = ["Sean Bowe"]
language = "en"
src = "src"
title = "The Ragu Book"

[preprocessor.katex]
macros = "macros.txt"
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "rust"
preferred-dark-theme = "rust"
additional-css = ["custom.css"]
hash-files = true

# Enable these to generate links with mdbook-rustdoc-link
# Do not check in these uncommented.
# [preprocessor.rustdoc-link]
# after = ["links"]
